init
LonelyBald/Pitsa pull request #1
Opened 2022-05-24 18:56 UTC by LonelyBald

2022-05-24 18:57 UTC, IvanAfonin commented on src/components/Categories.jsx
> +                <li>ВАНЯ ПИДОР</li>
Так делать не нада, но в целом пофиг

2022-05-24 18:58 UTC, IvanAfonin approved these changes
Sounds good, amazing :))

2022-08-22 09:08 UTC, IvanAfonin requested changes
Awesome work, you're crashing it, just fix this comments and do not forget about small commits :))

2022-08-22 09:08 UTC, IvanAfonin commented on .env
> +REACT_APP_BACKEND_URL="https://629de05cc6ef9335c0a8e475.mockapi.io/api/"
Add .env file to gitignore and create .env.example with example of .env implementation

2022-08-22 09:08 UTC, IvanAfonin commented on src/Context.tsx
> +export const HeaderContext = createContext({});
Please fix types for context

2022-08-22 09:08 UTC, IvanAfonin commented on src/components/CartEmpty.jsx
> +          Корзина пустая <icon>😕</icon>
Let's delete this emoji as discussed, also we had some error in console related to icon tag

2022-08-22 09:08 UTC, IvanAfonin commented on src/components/CartEmpty.jsx
> +          <br />
Create two <p> tags without <br> it can break layout in mobile devices

2022-08-22 09:08 UTC, IvanAfonin commented on src/components/CartEmpty.jsx
> +          <span>Вернуться назад</span>
Do we really need this span tag? Maybe it's possible to delete it and use only <Link>

2022-08-22 09:08 UTC, IvanAfonin commented on src/components/CartItem.jsx
> +import { CrossSVG } from '../assets/svgs/CrossSVG';
You can create index.ts file in svgs folder then import all svgs and export them using only one export

2022-08-22 09:08 UTC, IvanAfonin commented on src/components/CartItem.jsx
> +        type,
You can create a constant on the top and use this constant inside two methods (addItem, minusItem)

2022-08-22 09:08 UTC, IvanAfonin commented on src/components/Categories.jsx
> +  const categories = ['Все', 'Мясные', 'Вегетарианские', 'Гриль', 'Острые', 'Закрытые']
Create file constants.ts in the root directory and collect all constants in a project, you have a pizza type constant too

2022-08-22 09:08 UTC, IvanAfonin commented on src/components/DataFetchError.jsx
> +          Ошибка получения данных <icon>😕</icon>
Remove icon here too

2022-08-22 09:08 UTC, IvanAfonin commented on src/components/Header.tsx
> +import PizzaLogo from '../assets/img/pizza-logo.svg';
Create a pizza logo component and remove ts ignore here

2022-08-22 09:08 UTC, IvanAfonin commented on src/components/Header.tsx
> +import CartSVG from '../assets/img/cart.svg';
Create a cart svg component and remove ts ignore here

2022-08-22 09:08 UTC, IvanAfonin commented on src/components/Pagination/index.jsx
> +};
Please read docs for react-paginate and create dynamic pagination for any amount of items

2022-08-22 09:08 UTC, IvanAfonin commented on src/components/PizzaBlock.tsx
> +    dispatch(addItem(item));
This constant looks redundant use object inside action argument
```suggestion
    dispatch(addItem({
      id,
      title,
      price,
      imageUrl,
      type: typeNames[activeType],
      size: sizes[activeSize],
    }));
```

2022-08-22 09:08 UTC, IvanAfonin commented on src/components/PizzaBlock.tsx
> +export default PizzaBlock;
Please no default exports, try to use named exports only

2022-08-22 09:08 UTC, IvanAfonin commented on src/components/Search/index.jsx
> +    setValue('');
What is the difference between these two methods, maybe we can remove one of them?

2022-08-22 09:08 UTC, IvanAfonin commented on src/components/Sort.jsx
> +];
Use a constant file for storing constants, remove this one from here and add it to constants.ts

2022-08-22 09:08 UTC, IvanAfonin commented on src/components/Sort.jsx
> +      )}
You can remove this useless empty string

2022-08-22 09:08 UTC, IvanAfonin commented on src/components/Sort.jsx
> +      {open ? (
Please use && for this purposes(when your"else" statement is empty)

2022-08-22 09:08 UTC, IvanAfonin commented on src/components/Sort.jsx
> +export default Sort;
Default export :))

2022-08-22 09:08 UTC, IvanAfonin commented on src/index.tsx
> +import EmptyCart from './pages/NotFound';
Create index.ts inside the pages repository for more cleaner imports

2022-08-22 09:08 UTC, IvanAfonin commented on src/pages/Cart.tsx
> +    if (window.confirm('Вы хотити очистить корзину?')) {
Try to avoid using plain strings, it's better to create a constant on the top of the page and use it here

2022-08-22 09:08 UTC, IvanAfonin commented on src/pages/Cart.tsx
> +            </div>
Do not forget refactor styles here :))

2022-08-22 09:08 UTC, IvanAfonin commented on src/pages/Cart.tsx
> +export default Cart;
Default export :))

2022-08-22 09:08 UTC, IvanAfonin commented on src/pages/Menu.tsx
> +import PizzaBlock from '../components/PizzaBlock';
Let's create index.ts file with export inside components folder

2022-08-22 09:08 UTC, IvanAfonin commented on src/pages/Menu.tsx
> +  const search = searchValue ? `&search=${searchValue}` : '';
Let's try to refactor this code, maybe you have any suggestions?

2022-08-22 09:08 UTC, IvanAfonin commented on src/pages/Menu.tsx
> +      );
I think we can use some router hook for this purposes

2022-08-22 09:08 UTC, IvanAfonin commented on src/pages/Menu.tsx
> +export default Menu;
Default export

2022-08-22 09:08 UTC, IvanAfonin commented on src/pages/NotFound.jsx
> +              Корзина пустая <icon>😕</icon>
Please delete this icon and I think that you have too many same components related to cart

2022-08-22 09:08 UTC, IvanAfonin commented on src/redux/slices/cartSlice.ts
> +    //TODO: refactor minus item logic
Please remove this TODO cause we've already fixed this issue

2022-08-22 09:08 UTC, IvanAfonin commented on src/redux/slices/filterSlice.ts
> +  sort: { name: 'популярности', sortProperty: 'rating' },
It's better to create constants for name and sortPropety

2022-08-22 09:08 UTC, IvanAfonin commented on src/redux/thunk/getPitsaListThunk.ts
> +    );
You can try to create axios instance and use it here :))

2022-08-25 16:39 UTC, LonelyBald commented on src/components/Pagination/index.jsx
> +};
It's hard to implement, because fields cant be recived from API.

2022-08-25 20:58 UTC, merged